# Generated by Django 5.2.7 on 2025-10-21 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Tous les jours"),
                            ("twice_week", "Deux fois par semaine"),
                            ("thrice_week", "Trois fois par semaine"),
                            ("weekly", "Une fois par semaine"),
                            ("never", "Jamais"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Fréquence des emails",
                    ),
                ),
                (
                    "receive_emails",
                    models.BooleanField(
                        default=True, verbose_name="Recevoir des emails"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
    ]
