# Generated by Django 5.2.7 on 2025-10-21 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Centre d'intérêt",
                "verbose_name_plural": "Centres d'intérêt",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("scientific", "Publication scientifique"),
                            ("journal", "Revue"),
                            ("blog", "Blog"),
                            ("news", "Actualités"),
                        ],
                        max_length=20,
                        verbose_name="Type de source",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_scraped",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier scraping"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titre")),
                ("url", models.URLField(unique=True, verbose_name="URL")),
                ("summary", models.TextField(blank=True, verbose_name="Résumé")),
                ("content", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "author",
                    models.CharField(blank=True, max_length=200, verbose_name="Auteur"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Image URL")),
                (
                    "scraped_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Scrapé le"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="core.interest",
                        verbose_name="Centres d'intérêt",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="core.source",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_date", "-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="UserArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_bookmarked",
                    models.BooleanField(default=False, verbose_name="Favori"),
                ),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="Recommandé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="core.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article utilisateur",
                "verbose_name_plural": "Articles utilisateurs",
                "ordering": ["-created_at"],
                "unique_together": {("user", "article")},
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.interest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intérêt utilisateur",
                "verbose_name_plural": "Intérêts utilisateurs",
                "unique_together": {("user", "interest")},
            },
        ),
    ]
